### ISSUE TITLE
How can I contribute?

### ISSUE THREAD

**Issue by fx-biocoder** [Every2/doom#2]
Hey,

I'm currently improving my C++ skills, and thought it would be a good idea to contribute to another project. Would it be okay if I make a few pull requests in my free time? Please tell me more about the project (the general idea, specific stuff, etc) so I can start working on it as soon as possible.

**Comment by fx-biocoder** [comment]
Great, thanks for the video. I'll see what I can do, might take a few days to properly design the program before writing the actual code.

**Comment by Every2** [comment]
I will close this issue. Ty for the interest!
